<?php

$inc=array('Emo-R4sth4.php',);
include $inc[rand(0,count($inc)-1)];
$Tangan_R4sth4 = $R4sth4_EMO_tangan[rand(0,count($R4sth4_EMO_tangan)-1)];

$emoji=array(
urldecode('%F3%BE%80%80'),
urldecode('%F3%BE%80%81'),
urldecode('%F3%BE%80%82'),
urldecode('%F3%BE%80%83'),
urldecode('%F3%BE%80%84'),
urldecode('%F3%BE%80%85'),
urldecode('%F3%BE%80%87'),
urldecode('%F3%BE%80%B8'),
urldecode('%F3%BE%80%BC'),
urldecode('%F3%BE%80%BD'),
urldecode('%F3%BE%80%BE'),
urldecode('%F3%BE%80%BF'),
urldecode('%F3%BE%81%80'),
urldecode('%F3%BE%81%81'),
urldecode('%F3%BE%81%82'),
urldecode('%F3%BE%81%83'),
urldecode('%F3%BE%81%85'),
urldecode('%F3%BE%81%86'),
urldecode('%F3%BE%81%87'),
urldecode('%F3%BE%81%88'),
urldecode('%F3%BE%81%89'),
urldecode('%F3%BE%81%91'),
urldecode('%F3%BE%81%92'),
urldecode('%F3%BE%81%93'),
urldecode('%F3%BE%86%90'),
urldecode('%F3%BE%AB%BA'),
urldecode('%F3%BE%AB%BB'),
urldecode('%F3%BE%86%96'),
urldecode('%F3%BE%86%9B'),
urldecode('%F3%BE%86%9C'),
urldecode('%F3%BE%86%9D'),
urldecode('%F3%BE%86%9E'),
urldecode('%F3%BE%86%A0'),
urldecode('%F3%BE%86%A1'),
urldecode('%F3%BE%86%A2'),
urldecode('%F3%BE%86%A4'),
urldecode('%F3%BE%86%A5'),
urldecode('%F3%BE%86%A6'),
urldecode('%F3%BE%86%A7'),
urldecode('%F3%BE%86%A8'),
urldecode('%F3%BE%86%A9'),
urldecode('%F3%BE%86%AA'),
urldecode('%F3%BE%86%AB'),
urldecode('%F3%BE%86%AE'),
urldecode('%F3%BE%86%AF'),
urldecode('%F3%BE%86%B0'),
urldecode('%F3%BE%86%B1'),
urldecode('%F3%BE%86%B2'),
urldecode('%F3%BE%86%B3'),
urldecode('%F3%BE%86%B5'),
urldecode('%F3%BE%94%97'),
urldecode('%F3%BE%94%98'),
urldecode('%F3%BE%94%99'),
urldecode('%F3%BE%94%9A'),
urldecode('%F3%BE%94%9C'),
urldecode('%F3%BE%94%9E'),
urldecode('%F3%BE%94%9F'),
urldecode('%F3%BE%94%A4'),
urldecode('%F3%BE%94%A5'),
urldecode('%F3%BE%94%A6'),
urldecode('%F3%BE%94%A8'),
urldecode('%F3%BE%94%B8'),
urldecode('%F3%BE%94%BC'),
urldecode('%F3%BE%94%BD'),
urldecode('%F3%BE%9F%9C'),
urldecode('%F3%BE%A0%93'),
urldecode('%F3%BE%A0%94'),
urldecode('%F3%BE%A0%9A'),
urldecode('%F3%BE%A0%9C'),
urldecode('%F3%BE%A0%9D'),
urldecode('%F3%BE%A0%9E'),
urldecode('%F3%BE%A0%A3'),
);
$fathul1=$emoji[rand(0,count($emoji)-1)];
$fathul2=$emoji[rand(0,count($emoji)-1)];
$fathul3=$emoji[rand(0,count($emoji)-1)];
$fathul4=$emoji[rand(0,count($emoji)-1)];
$fathul5=$emoji[rand(0,count($emoji)-1)];
$fathul6=$emoji[rand(0,count($emoji)-1)];
$fathul7=$emoji[rand(0,count($emoji)-1)];
$fathul8=$emoji[rand(0,count($emoji)-1)];
$fathul9=$emoji[rand(0,count($emoji)-1)];
$fathul10=$emoji[rand(0,count($emoji)-1)];
$fathul11=$emoji[rand(0,count($emoji)-1)];
$fathul12=$emoji[rand(0,count($emoji)-1)];
$fathul13=$emoji[rand(0,count($emoji)-1)];
$fathul14=$emoji[rand(0,count($emoji)-1)];
$fathul15=$emoji[rand(0,count($emoji)-1)];
$fathul16=$emoji[rand(0,count($emoji)-1)];
$fathul17=$emoji[rand(0,count($emoji)-1)];
$fathul18=$emoji[rand(0,count($emoji)-1)];
$fathul19=$emoji[rand(0,count($emoji)-1)];
$fathul20=$emoji[rand(0,count($emoji)-1)];
$fathul21=$emoji[rand(0,count($emoji)-1)];
$fathul22=$emoji[rand(0,count($emoji)-1)];
$fathul23=$emoji[rand(0,count($emoji)-1)];
$fathul24=$emoji[rand(0,count($emoji)-1)];
$fathul25=$emoji[rand(0,count($emoji)-1)];
$fathul26=$emoji[rand(0,count($emoji)-1)];
$fathul27=$emoji[rand(0,count($emoji)-1)];
$fathul28=$emoji[rand(0,count($emoji)-1)];
$fathul29=$emoji[rand(0,count($emoji)-1)];
$fathul30=$emoji[rand(0,count($emoji)-1)];
$fathul31=$emoji[rand(0,count($emoji)-1)];
$fathul32=$emoji[rand(0,count($emoji)-1)];
$fathul33=$emoji[rand(0,count($emoji)-1)];
$fathul34=$emoji[rand(0,count($emoji)-1)];
$fathul35=$emoji[rand(0,count($emoji)-1)];
$fathul36=$emoji[rand(0,count($emoji)-1)];
$fathul37=$emoji[rand(0,count($emoji)-1)];
$fathul38=$emoji[rand(0,count($emoji)-1)];
$fathul39=$emoji[rand(0,count($emoji)-1)];
$fathul40=$emoji[rand(0,count($emoji)-1)];
$fathul41=$emoji[rand(0,count($emoji)-1)];
$fathul42=$emoji[rand(0,count($emoji)-1)];
$fathul43=$emoji[rand(0,count($emoji)-1)];
$fathul44=$emoji[rand(0,count($emoji)-1)];
$fathul45=$emoji[rand(0,count($emoji)-1)];
$fathul46=$emoji[rand(0,count($emoji)-1)];
$fathul47=$emoji[rand(0,count($emoji)-1)];
$fathul48=$emoji[rand(0,count($emoji)-1)];
$fathul49=$emoji[rand(0,count($emoji)-1)];
$fathul50=$emoji[rand(0,count($emoji)-1)];
$fathul51=$emoji[rand(0,count($emoji)-1)];
$fathul52=$emoji[rand(0,count($emoji)-1)];
$fathul53=$emoji[rand(0,count($emoji)-1)];
$fathul54=$emoji[rand(0,count($emoji)-1)];
$fathul55=$emoji[rand(0,count($emoji)-1)];
$fathul56=$emoji[rand(0,count($emoji)-1)];
$fathul57=$emoji[rand(0,count($emoji)-1)];
$fathul58=$emoji[rand(0,count($emoji)-1)];
$fathul59=$emoji[rand(0,count($emoji)-1)];
$fathul60=$emoji[rand(0,count($emoji)-1)];
$fathul61=$emoji[rand(0,count($emoji)-1)];
$fathul62=$emoji[rand(0,count($emoji)-1)];
$fathul63=$emoji[rand(0,count($emoji)-1)];
$fathul64=$emoji[rand(0,count($emoji)-1)];
$fathul65=$emoji[rand(0,count($emoji)-1)];
$fathul66=$emoji[rand(0,count($emoji)-1)];
$fathul67=$emoji[rand(0,count($emoji)-1)];
$fathul68=$emoji[rand(0,count($emoji)-1)];
$fathul69=$emoji[rand(0,count($emoji)-1)];
$fathul70=$emoji[rand(0,count($emoji)-1)];
$fathul71=$emoji[rand(0,count($emoji)-1)];

$text1 = array('(^3^_'.$fathul1.'_o_'.$fathul2.'_ o _'.$fathul3.'_o_'.$fathul4.'_^3^)','
'.$fathul1.' ^_~ お ~ｏ '.$fathul3.' (⌒0⌒)ｏは '.$fathul4.'',' '.$fathul1.' '.$fathul2.' ¯(ツ)/¯( >͡ .̮ Ơ̴͡ )*¯(ツ)/¯ '.$fathul3.' '.$fathul4.'',''.$fathul3.' ♪(・o･)┛♪┗ ( ･o･) ┓♪┏ (・o･)♪ '.$fathul1.' ',''.$fathul4.' ( ⌣ ́_⌣ ̀)ヾ( '.$fathul1.' '.$fathul3.' )ノ( ⌣ ́_⌣ ̀) '.$fathul3.'',''.$fathul3.' '.$fathul2.' ヾ(★´Д)人(Д｀☆)ノ゛ '.$fathul1.' '.$fathul4.' ',''.$fathul3.' ...,,,,, '.$fathul1.' ¦[-_-]¦ '.$fathul2.' ,,,,,... '.$fathul4.'',''.$fathul2.' '.$fathul1.' -̩̩̩-̩̩̩-̩̩̩-̩̩̩-̩̩̩-___̩̩̩-̩̩̩-̩̩̩-̩̩̩-̩̩̩-̩̩̩- ̩̩̩) '.$fathul1.' '.$fathul4.'',''.$fathul3.' '.$fathul2.' ヾ(★´Д)人(Д｀☆)ノ゛ '.$fathul1.' '.$fathul4.'',''.$fathul3.' ¸LoV3¸(´３`） '.$fathul4.' ﾉ♪(*^ ・^)ノ⌒☆ '.$fathul1.'',''.$fathul3.' ( ⌣ ́_ ⌣ ̀)ヾ '.$fathul4.' (´ー｀)ノ '.$fathul1.' ( ⌣ ́_ ⌣ ̀) '.$fathul2.'','~(˘▾ '.$fathul1.' ˘~) ~(˘▾ '.$fathul2.' ˘)~ (~˘▾ '.$fathul3.' ˘)~',''.$fathul4.' __,,,@,,-- '.$fathul1.' '.$fathul2.' --,,@,,,__ '.$fathul1.'','(.⌣_ '.$fathul1.' _⌣.)з ｡_(-＿-*)OFF...! '.$fathul2.'','(_¸.•´(_¸.•´* '.$fathul2.' '.$fathul1.' '.$fathul3.' *•.¸_)• .¸_)',''.$fathul2.' （＾ｖ＾） '.$fathul1.'（＾ｖ＾） '.$fathul3.'','
'.$fathul1.' '.$fathul2.' ¯(ツ)/¯( >͡ .̮ Ơ̴͡ )*¯(ツ)/¯ '.$fathul4.' '.$fathul3.'','
'.$fathul1.' \(´▽`)/ \(´▽`)/ \(´▽`)/ '.$fathul2.'','ヾ(ﾟдﾟ*三*ﾟдﾟ)ノ '.$fathul1.' ＼(^ω^＼)( /^ω^)/',''.$fathul2.' (.⌣__⌣.)з ｡_(-＿-*)OFF...! '.$fathul4.'','ヾ(ﾟдﾟ*三*ﾟдﾟ)ノ '.$fathul4.' ＼(^ω^＼)( /^ω^)/','
(˘ '.$fathul2.' ⌣˘)ʃ smileƪ(˘⌣ '.$fathul4.' ˘)cheeseƪ(˘ '.$fathul1.' ⌣˘)',''.$fathul1.' (ノ＾ω＾)ハ(＾ω＾ )ノ( ˘ з˘ )♬♪ '.$fathul2.'',''.$fathul2.' (ˆڡ ˆ)*•.¸*•.¸(っ˘з˘)っ¸.•*¸.•*(ˆ ڡ ˆ) '.$fathul1.'
 ',); 
?>